
package com.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T16:29:28.350-04:00
 * Generated source version: 3.1.12
 * 
 */
public final class ComWebserviceISubstraction_SubstractionPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webservice.com", "SubstractionService");

    private ComWebserviceISubstraction_SubstractionPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SubstractionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SubstractionService ss = new SubstractionService(wsdlURL, SERVICE_NAME);
        ComWebserviceISubstraction port = ss.getSubstractionPort();  
        
        {
        System.out.println("Invoking substract...");
        int _substract_arg0 = 1145322518;
        int _substract_arg1 = 1745585098;
        int _substract__return = port.substract(_substract_arg0, _substract_arg1);
        System.out.println("substract.result=" + _substract__return);


        }

        System.exit(0);
    }

}
