package com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T16:29:28.422-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.webservice.com", name = "com.webservice.ISubstraction")
@XmlSeeAlso({ObjectFactory.class})
public interface ComWebserviceISubstraction {

    @WebMethod(action = "urn:Substract")
    @RequestWrapper(localName = "substract", targetNamespace = "http://www.webservice.com", className = "com.webservice.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.SubstractResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int substract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
