package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T16:29:28.429-04:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SubstractionService", 
                  wsdlLocation = "file:/home/lbs/dev/java/ws1z0808/MyWebConsuming/WebContent/wsdl/SubstractionPort.wsdl",
                  targetNamespace = "http://www.webservice.com") 
public class SubstractionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.webservice.com", "SubstractionService");
    public final static QName SubstractionPort = new QName("http://www.webservice.com", "SubstractionPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/lbs/dev/java/ws1z0808/MyWebConsuming/WebContent/wsdl/SubstractionPort.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SubstractionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/lbs/dev/java/ws1z0808/MyWebConsuming/WebContent/wsdl/SubstractionPort.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SubstractionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubstractionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubstractionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SubstractionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SubstractionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SubstractionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ComWebserviceISubstraction
     */
    @WebEndpoint(name = "SubstractionPort")
    public ComWebserviceISubstraction getSubstractionPort() {
        return super.getPort(SubstractionPort, ComWebserviceISubstraction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComWebserviceISubstraction
     */
    @WebEndpoint(name = "SubstractionPort")
    public ComWebserviceISubstraction getSubstractionPort(WebServiceFeature... features) {
        return super.getPort(SubstractionPort, ComWebserviceISubstraction.class, features);
    }

}
