
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-28T16:29:28.411-04:00
 * Generated source version: 3.1.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "SubstractionService",
                      portName = "SubstractionPort",
                      targetNamespace = "http://www.webservice.com",
                      wsdlLocation = "file:/home/lbs/dev/java/ws1z0808/MyWebConsuming/WebContent/wsdl/SubstractionPort.wsdl",
                      endpointInterface = "com.webservice.ComWebserviceISubstraction")
                      
public class SubstractionPortImpl implements ComWebserviceISubstraction {

    private static final Logger LOG = Logger.getLogger(SubstractionPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.webservice.ComWebserviceISubstraction#substract(int arg0, int arg1)*
     */
    public int substract(int arg0, int arg1) { 
        LOG.info("Executing operation substract");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 1682403488;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
