
package com.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.12
 * Mon Aug 28 16:08:58 EDT 2017
 * Generated source version: 3.1.12
 */

@XmlRootElement(name = "substractResponse", namespace = "http://www.webservice.com")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "substractResponse", namespace = "http://www.webservice.com")

public class SubstractResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

